### ISSUE TITLE
Bugs Tracking Board

### ISSUE THREAD

**Issue by BPA98** [404TeamNameNotFound404/ProjectDetective#3]
Know bugs 
- [x] Head Bobbing won't stop if the player moves diagonally on Gamepad
- [x] Mouse Motions axis inverted for keyboard only
- [x] Detective Photocamera won't assign the Detective player as reference
- [x] Detective Photocamera won't zoom out

**Comment by Graaced** [comment]
- [x] Y axis is inverted ??

**Comment by BPA98** [comment]
> * [x]  Y axis is inverted 
Y axis only

**Comment by SimoneDellaRocca** [comment]
movement:
- [x] speed maybe tied to framerate?
- [x] interpolation between standing and crouch
- [x] crouch has to be toggle (no hold)

**Comment by BPA98** [comment]
- [x] Evidence being detected through walls

**Comment by SimoneDellaRocca** [comment]
detective camera:

- [x] print string for EvidencePhotoMinSpace and EvidenceInPhotoPercentage values

**Comment by BPA98** [comment]
Evidence System:

- [x] Ignored Actor TArray is always null despite being correctly populated
